title: kumararnav
subtitle: AI Intern
description: >- # this means to ignore newlines until "baseurl:"
 Arnav's personal website

url: "https://kumararnav.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Project
      url: /project
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact
    #   url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: arnav.png
author: Kumar Arnav
author_bio: Hi, my name is Kumar Arnav. I built this site to showcase my portfolio :D
author_email: "the.kumar.arnav@gmail.com"
author_location: USA
# author_website_url: "https://sujaykundu.com"
typewrite-text: Just a guy who loves cyber security, AI and gaming.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: PlanetArt
              company_logo: planetart_com_logo.png
              company_url: https://www.planetart.com/
              designation: AI Intern (June 2024 - Present)
              description:
                - Developed an advanced voice-to-voice bot model hosted on AWS, enabling multilingual interactions by processing user inputs and generating responses in the same language.
                - Implemented novel interruption and user speech understandability features.
                - Enabled the LLM to determine when a user had finished speaking, allowing it to wait for the user to complete their thoughts.
                - Accurately detected user interruptions, enhancing the fluidity and responsiveness of interactions.
                - Integrated backend systems and ensured model feasibility to support optimal performance.
                - Trained the model, focusing on improving accuracy and responsiveness to user inputs.
                - Gained hands-on experience in AI model deployment, backend development, and innovative interaction design.
              visibility: true


            - company_name: University of Southern California
              company_logo: usc_logo.png
              company_url: https://www.usc.edu/
              designation: Research Assistant
              description: 
                - Constructed a reinforcement machine learning-based model for Incremental View Maintenance(IVM) techniques for PostgreSQL achieving approx 53% faster runtime for all queries.
                - Explored the effectiveness of using reversed input files in singing voice deepfake detection, demonstrating significant improvements in Equal Error Rate (EER) across various fusion methods.
                - Conducted and completed experiments using RawNet and LFCC models, evaluating their performance in detecting deepfake singing voices.
                - Collaborating with a research team to finalize and present detailed EER comparisons, contributing to advancements in the field of deepfake detection.
              visibility: true

            - company_name: Upwork
              company_logo: upwork_logo.png
              company_url: https://www.upwork.com/
              designation: Freelance Machine Learning Engineer
              description:  
                - Deployed a Random Forest model to surmise customer churn for an e-commerce company, resulting in a 18% reduction in churn rate
                - Trained a Gradient Boosting Machine (GBM) algorithm to optimize advertising campaigns for a marketing agency, increasing click-through rates by 27%
                - Trained a Support Vector Machine (SVM) model to anticipate machine failure for a manufacturing company, reducing unplanned downtime by 32%
                - Performed Natural Language Processing (NLP) techniques deploying LSTM networks for sentiment analysis for a social media analytics firm, boosting brand monitoring accuracy by 78%

            - company_name: Solvaphile
              company_logo: solvaphile_logo.png
              company_url: https://www.solvaphile.com/
              designation: Subject Matter Expert (SME)
              description: 
                - Applied vision system for an autonomous drone deploying Convolutional Neural Networks (CNN) to identify and differentiate objects and obstacles, enhancing navigational accuracy by 59%
                - Accomplished object recognition and distance estimation algorithms, improving drone's retrieval success rate by 80%
              visibility: true
              
            - company_name: MissionEd
              company_logo: missioned_logo.png
              company_url: https://www.missioned.org/
              designation: Application Developer
              description:  
                - Led development of a user-centric Android app (Java) for matching students and teachers based on availability of both students and teachers, enhancing user convenience and contributing to a 4.5-star rating on the Google Play Store
                - Directed backend team integrating Firebase for efficient data management, leading to a 82% improvement in data synchronization and communication between users,a critical component for app's time-matching functionality
                - Orchestrated comprehensive testing and debugging of application, leading to a 43% reduction in bug reports and ensuring a 95% crash-free user experience
                - Managed deployment of app on Google Play Store, adhering to all guidelines and accomplishing 10,000+ downloads within first three months of launch
              visibility: true
              
            - company_name: Cyber Zone Technologies (P) Ltd.
              company_logo: cyberzone_logo.png
              company_url: https://www.cyberzone.org.in/
              designation: Ethical Hacker
              description:
                - Identified vulnerabilities and breakpoints in 300+ websites and Android applications for clients as an ethical hacker, operating under strict non-disclosure agreements prevent sharing of specific details
                - Performed comprehensive security audits for mid-sized companies, resulting in a 70% improvement in cybersecurity practices based on confidential recommendations
              visibility: true


# Education
author_education_details:
              - college_logo: usc_logo.png
                college_name: University of Southern California
                college_url: https://www.usc.edu/
                college_degree: Master of Science (MS), Artificial Intelligence
                description: Pursuing a Master's in Artificial Intelligence with a focus on machine learning and deepfake detection research.
                visibility: true
                
              - college_logo: srm_logo.png
                college_name: SRM University
                college_url: https://www.srmist.edu.in/
                college_degree: Bachelor of Technology (BTech), Computer Science
                description: Graduated with a BTech in Computer Science, specializing in AI and software development.
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: xplor4r
github_username:  unforgettablexD
#instagram_username: xplor4r
# facebook_username: johndoe
linkedin_username: kumar-arnav-016675180
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe
kaggle_username: swaggy1

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: kumararnav
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: kumararnav

# # mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: the.kumar.arnav@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 10
per_page: 10
paginate_path: "/blog/page/:num/"
project_paginate_path: "/project/page/:num/"
# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  project_posts:
    output: true
    paginate: true
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /project/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: true

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
